#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE="dokku/$APP"

echo "-----> Injecting vapor dependencies ..."

DIR=/app

COMMAND=$(cat <<EOF
export DEBIAN_FRONTEND=noninteractive
if [ -f $DIR/.vapor-dependencies ]; then
    echo "-----> vapor dependencies detected"
    apt-get update
    apt-get install -y wget software-properties-common python-software-properties apt-transport-https
    wget https://repo.vapor.codes/apt/keyring.gpg -O- | apt-key add -
    echo "deb https://repo.vapor.codes/apt xenial main" | tee /etc/apt/sources.list.d/vapor.list
    apt-get update
    PACKAGES=\$(cat "$DIR/.vapor-dependencies") | tr "\\n" " ")
    apt-get install -y \$PACKAGES
    echo "-----> Injected vapor dependencies: \$PACKAGES"
fi
sleep 1
EOF
)

id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
#enable logs
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null

